<div class="header__top">
  <div class="header__top__inner">
    <div class="header__logo">
      <a href="/">
        <img alt="The Nation's Report Card" src="/adminonly/themes/redesign_2015/images/nationsreportcard-logo.png">
      </a>
    </div>
    <nav role="navigation">
      <ul class="nav-menu nav--utility">
        <li class="nav-item">
          <div class="nav-heading" tabindex="0" id="accessible-megamenu-1623097345678-1" aria-haspopup="true" aria-controls="accessible-megamenu-1623097345678-2" aria-expanded="false">Reports</div>
          <div class="sub-nav reports" id="accessible-megamenu-1623097345678-2" role="group" aria-expanded="false" aria-hidden="true" aria-labelledby="accessible-megamenu-1623097345678-1">
            <ul class="sub-nav-group">
              <li class="sub-nav-section">
                <div class="">Current Releases</div>
                <ul>
                  <li class="">
                    <a href="/arts_2016/">Arts</a>
                  </li>
                  <li>
                    <div class="">Civics</div>
                    <ul>                           
                      <li>
                        <a href="/highlights/civics/2018/" class="">Highlights from the 2018 Assessment</a>
                      </li>
                      <li class="">
                        <a href="/civics/" class="">Report Card</a>
                      </li>
                    </ul>
                  </li>
                  <li class="">
                    <a href="/economics_2012/">Economics</a>
                  </li>
                  <li>
                    <div class="">Geography</div>
                    <ul>                           
                      <li>
                        <a href="/highlights/geography/2018/" class="">Highlights from the 2018 Assessment</a>
                      </li>
                      <li>
                        <a href="/geography/" class="">Report Card</a>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <a href="/ltt_2012/" class="">Long-Term Trend</a>
                  </li>
                  <li>
                    <div class="">Mathematics</div>
                    <ul>                           
                      <li>
                        <a href="/highlights/mathematics/2019/">Highlights from the 2019 Grade 4 and 8 Assessment</a>
                      </li>
                      <li>
                        <a href="/mathematics/?grade=4">Report Card for the Nation, States, and Districts (grades 4 and 8)</a>
                      </li>
                      <li>
                        <a href="/highlights/mathematics/2019/g12/">Highlights from the 2019 Grade 12 Assessment</a>
                      </li>
                      <li>
                        <a href="/mathematics/?grade=12">Report Card for Grade 12</a>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <div>Reading</div>
                    <ul>                            
                      <li>
                        <a href="/highlights/reading/2019/">Highlights from the 2019 Grades 4 and 8 Assessment</a>
                      </li>
                      <li>
                        <a href="/reading/?grade=4">Report Card for the Nation, States, and Districts (grades 4 and 8)</a>
                      </li>
                      <li>
                        <a href="/highlights/reading/2019/g12/">Highlights from the 2019 Grade 12 Assessment</a>
                      </li>
                      <li>
                        <a href="/reading/?grade=12">Report Card for Grade 12</a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
            </ul>
            <ul class="sub-nav-group">
              <li class="sub-nav-section">
                <ul>
                  <li>
                    <div><br>Science</div>
                    <ul>
                      <li>
                        <a href="/highlights/science/2019/">Highlights from the 2019 Assessment</a>
                      </li>
                      <li>
                        <a href="/science/">2019 Report Card for the Nation</a>
                      </li>
                      <li>
                        <a href="/science_2015/#overview/accordion-3?grade=4">2015 State Assessment</a>
                      </li>
                      <li>
                        <a href="/science_2009/district_summary.aspx">2009 Trial Urban District Assessment</a>
                      </li>
                      
                    </ul>
                  </li>
                  <li>
                    <div>Survey Questionnaires</div>
                    <ul>
                      <li>
                        <a href="/sq_students_views_2015/">Students' Views of Mathematics, Reading, and Science</a>
                      </li>
                      <li>
                        <a href="/sq_computer/">Students' Computer Access and Use</a>
                      </li>
                      <li>
                        <a href="/sq_classroom/">Classroom Instruction for Mathematics, Reading, and Science</a>
                      </li>
                    </ul>
                  </li>

                  <li>
                    <div>Technology and Engineering Literacy</div>
                    <ul>
                      <li>
                        <a href="/tel_2018_highlights/">Highlights from the 2018 Assessment</a>
                      </li>
                      <li>
                        <a href="/tel/">Report Card</a>
                      </li>
                    </ul>
                  </li>

                  <li>
                    <div>U.S. History</div>
                    <ul>                           
                      <li>
                        <a href="/highlights/ushistory/2018/">Highlights from the 2018 Assessment</a>
                      </li>
                      <li>
                        <a href="/ushistory/">Report Card</a>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <div>Writing</div>
                    <ul>
                      <li>
                        <a href="/writing_2011/">National</a>
                      </li>
                      <li>
                        <a href="/writing_2007/w0037.aspx">Trial Urban District Assessment</a>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li class="sub-nav-section">
                <br>
                <br>
                <a href="/report_archive.aspx">Report Library</a>
              </li>
            </ul>
            <div class="nav-vertical-devider"></div>
            <ul class="sub-nav-group">
              <li class="sub-nav-section">
                <div>Special Studies</div>
                <ul>
                  <li>
                    <a href="/process_data/">2017 Mathematics Process Data</a>
                  </li>
                  <li>
                    <a href="/hsts_2009/">High School Transcript Study</a>
                  </li>
                  <li>
                    <a href="/megastates/">Mega-States</a>
                  </li>
                  <li>
                    <a href="/puerto_rico_2013/#/">Mathematics Puerto Rico</a>
                  </li>
                  <li>
                    <a href="/reading_2013/vocabulary/">Vocabulary</a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <div class="nav-heading" tabindex="0" id="accessible-megamenu-1623097345681-3" aria-haspopup="true" aria-controls="accessible-megamenu-1623097345681-4" aria-expanded="false">Dashboards</div>
          <div class="sub-nav" id="accessible-megamenu-1623097345681-4" role="group" aria-expanded="false" aria-hidden="true" aria-labelledby="accessible-megamenu-1623097345681-3">
            <ul class="sub-nav-group">
              <li>
                <a href="/dashboards/achievement_gaps.aspx" class="">Achievement Gap Dashboard</a>
              </li>
              <li>
                <a href="/dashboards/schools_dashboard.aspx" class="">Public, Private, and Charter Schools Dashboard</a>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <div class="nav-heading" tabindex="0" id="accessible-megamenu-1623097345684-5" aria-haspopup="true" aria-controls="accessible-megamenu-1623097345684-6" aria-expanded="false">Data Tools</div>
          <div class="sub-nav" id="accessible-megamenu-1623097345684-6" role="group" aria-expanded="false" aria-hidden="true" aria-labelledby="accessible-megamenu-1623097345684-5">
            <ul class="sub-nav-group">
              <li>
                <a href="/data_tools.aspx" class="">Data Tools Home</a>
              </li>
              <li class="">
                <a href="/ndecore/" class="">Data Explorer</a>
              </li>

              <li class="">
                <a href="/profiles/stateprofile/">State Profiles</a>
              </li>
              <li class="">
                <a href="/profiles/districtprofile/">District Profiles</a>
              </li>
              <li>
                <a href="/api_documentation.aspx">NAEP Data Service API</a>
              </li>
              <li>
                <a href="https://nces.ed.gov/nationsreportcard/nqt/">Questions Tool</a>
              </li>
              <li>
                <a href="/itemmaps/">Item Maps</a>
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <div class="nav-heading">
            <a href="/media.aspx" id="accessible-megamenu-1623097345685-7" aria-haspopup="true" aria-controls="accessible-megamenu-1623097345685-8" aria-expanded="false">Newsroom</a>
          </div>
          <div class="sub-nav" style="display:none;" id="accessible-megamenu-1623097345685-8" role="group" aria-expanded="false" aria-hidden="true" aria-labelledby="accessible-megamenu-1623097345685-7">
        </div></li>
        <li class="nav-item selected">
          <div class="nav-heading">
            <a href="/focus_on_naep/" id="accessible-megamenu-1623097345685-9" aria-haspopup="true" aria-controls="accessible-megamenu-1623097345685-10" aria-expanded="false">Focus on NAEP</a>
          </div>
          <div class="sub-nav" style="display:none;" id="accessible-megamenu-1623097345685-10" role="group" aria-expanded="false" aria-hidden="true" aria-labelledby="accessible-megamenu-1623097345685-9">
        </div></li>
        <li class="nav-item">
          <div class="nav-heading">
            <a href="/takenaepnow/" id="accessible-megamenu-1623097345686-11" aria-haspopup="true" aria-controls="accessible-megamenu-1623097345686-12" aria-expanded="false">Take NAEP Now</a>
          </div>
          <div class="sub-nav" style="display:none;" id="accessible-megamenu-1623097345686-12" role="group" aria-expanded="false" aria-hidden="true" aria-labelledby="accessible-megamenu-1623097345686-11">
        </div></li>
      </ul>
    </nav>
    <form action="/search/">
      <div class="search-box" tabindex="0" onkeypress="ToggleSearchButton(event)">
        <img alt="Select to Open Search" id="magnifier" class="magnifying-glass" src="/adminonly/themes/redesign_2015/images/mag.png" onclick="ToggleSearchButton(0)">
        <div id="search-container-id" class="hide-search-box">
          <img alt="Carrot Image" id="carrot-glass-id" class="carrot-image" src="/adminonly/themes/redesign_2015/images/carrot.png">
          <div class="search-container">
            <input name="q" title="Search Box" id="searchBox" type="text" maxlength="256" class="search-textbox" onblur="HideSearch(event)">
              <button title="Search Button" id="searchButton" type="submit" value="Search" class="search-button">
                <span class="search-text">SEARCH</span>
              </button> 
              <input name="output" type="hidden" value="xml_no_dtd">
                <input name="client" type="hidden" value="nces"> 
                  <input name="sort" type="hidden" value="date:D:L:d1">
                    <input name="entqr" type="hidden" value="3"> 
                      <input name="site" type="hidden" value="nationsreportcard">
                      </div>        
                    </div>
                  </div>
                </form>
              </div>
            </div>
<header id="header"><div class="header-bottom"><div class="header-bottom-inner"><div id="site-info"><h1 id="site-name"><strong>Focus</strong> <span>on</span> <strong>NAEP</strong></h1><h2>National Assessment of Educational Progress</h2></div><ul class="social-media"><li><a class="icon_email" title="Email this page" aria-label="Email this page" href="#">Email</a></li><li><a class="icon_print" title="Print this page" aria-label="Print this page" href="#">Print</a></li><li><a class="icon_twitter" title="Share this page on Twitter" aria-label="Share this page on Twitter" href="#">Twitter</a></li><li><a class="icon_facebook" title="Share this page on Facebook" aria-label="Share this page on Facebook" href="#">Facebook</a></li></ul></div></div></header>