<div id="header">
    <div class="header__bottom">
      <div class="header__bottom__inner">
        <h1 class="site-name">
          <strong class="site-name__title">Focus</strong><span class="site-name__mid">on</span><strong
            class="site-name__content">NAEP</strong>
        </h1>
        <h2 class="site-name__text">
          <span>National Assessment of Educational Progress</span>
        </h2>
        <ul class="social-media">
          <li>
            <a class="icon_email" title="Email this page" aria-label="Email this page" href="#"
              onclick="EmailCurrentPage(event)">Email</a>
          </li>
          <li>
            <a class="icon_print" title="Print this page" aria-label="Print this page" href="#"
              onclick="PrintCurrentPage(event)">Print</a>
          </li>
          <li>
            <a class="icon_twitter" title="Share this page on Twitter" aria-label="Share this page on Twitter" href="#"
              onclick="ShareonTwitter(event)">Twitter</a>
          </li>
          <li>
            <a class="icon_facebook" title="Share this page on Facebook" aria-label="Share this page on Facebook"
              href="#" onclick="ShareonFacebook(event)">Facebook</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <nav id="primary-nav">
    <div class="nav__inner">
      <ul class="section-selector">
        <li><span><a class="active" href="#" data-section="home">Home</a></span></li>
        <li><span><a href="#" data-section="theme1">NAEP Theme1</a></span></li>
        <li><span><a href="#" data-section="theme2">NAEP Theme2</a></span></li>
      </ul>
    </div>
  </nav>