<footer class="fon-footer">
  <div class="fon-footer__inner">
    <div class="fon-footer__left">
      <div class="fon-footer__reference">
        <div class="fon-footer__wrapper--flex">
          <div class="fon-footer__nces-contact">
            <a
              href="http://nces.ed.gov/"
              class="fon-footer__ies-link"
              title="Connect on nces.ed.gov"
              aria-label="Icon of IES"
            ></a
            ><br />
            <div class="fon-footer__address fon-footer__address--right">
              <span>National Center for Education Statistics</span><br /><span
                >Institute of Education Sciences</span
              ><br /><span>Potomac Center Plaza</span><br /><span
                >550 12th Street SW</span
              ><br /><span>Washington, DC 20202</span>
            </div>
          </div>
        </div>
      </div>
      <p>
        Prepared for the National Center for Education Statistics under Contract
        No.ED-IES-12-D-0002 with the American Institutes for Research.
      </p>
    </div>
    <div class="fon-footer__right">
      <div class="fon-footer__link-heading">RELATED LINKS</div>
      <ul class="fon-footer__link-list">
        <ul>
          <li><a href="/about.aspx">About The Nation's Report Card</a></li>
          <li>
            <a href="http://nces.ed.gov/nationsreportcard/about/"
              >About the National Assessment of Educational Progress (NAEP)</a
            >
          </li>
          <li><a href="/contacts.aspx">Contacts</a></li>
          <li><a href="/faq.aspx">FAQs</a></li>
          <li><a href="/glossary.aspx?ispopup=false">Glossary</a></li>
        </ul>
      </ul>
      <div class="fon-footer__social-media">
        <span>FOLLOW US</span>
        <a
          class="icon_footer_twitter"
          title="Follow us on Twitter"
          aria-label="Follow us on Twitter"
          target="_blank"
          href="https://twitter.com/naep_nces"
          ><i class="fa fa-twitter" aria-hidden="true"></i> </a
        ><a
          target="_blank"
          class="icon_footer_facebook"
          title="Follow us on Facebook"
          aria-label="Follow us on Facebook"
          href="https://www.facebook.com/NationalAssessmentofEducationalProgress"
          ><i class="fa fa-facebook" aria-hidden="true"></i
        ></a>
      </div>
    </div>
  </div>
</footer>
